syntax = "proto3";
package authPackage;
service authService{
    rpc registerUser (registerRequest) returns (registerResponse);
    rpc loginUser (loginRequest) returns (loginResponse);
    rpc seeProfile (userRequest) returns (userResponse);
}

message userResponse {
    string id = 1;
    string name = 2;
    string email =3;
    string role =4; 
}

message userRequest {
    string user_id = 1;
}

message registerRequest{
  string name = 1;
  string email = 2;
  string password = 3; 
}

message registerResponse{
    userResponse user = 1;
}

message loginRequest {
    string email = 1;
    string password =2;
}

message loginResponse {
    userResponse user =1;
    string token = 2;
}
