syntax = "proto3";
package notificationPackage;

service notificationService {
  rpc createNotification (createNotificationReq) returns (createNotificationRes);
  rpc getNotificationByUser (getNotificationByUserReq) returns (getNotificationByUserRes);
  rpc markAsRead (markAsReadReq) returns (markAsReadRes);
  rpc getUnreadCount (getUnreadCountReq) returns (getUnreadCountRes);
}

message Notification {
  string id = 1;
  string user_id = 2;
  string type = 3;
  string payload = 4;
  string read_at = 5;
  string created_at = 6;
}


message createNotificationReq {
  string user_id = 1;
  string type = 2;
  string payload = 3;
}


message createNotificationRes {
  Notification notification = 1;
}


message getNotificationByUserReq {
  string user_id = 1;
  int32 page = 2;
  int32 limit = 3;
  bool unread_only = 4;
}


message getNotificationByUserRes {
  int32 count = 1;
  repeated Notification notifications = 2;
}


message markAsReadReq {
  string id = 1;
}


message markAsReadRes {
  string message = 1;
}


message getUnreadCountReq {
  string user_id = 1;
}


message getUnreadCountRes {
  int32 count = 1;
}
