syntax = "proto3";
package taskPackage;

// enum Status {
//     Pending = 0;
//     InProgress = 1;
//     Completed = 2;
// }

// enum Priority {
//     Medium =0;
//     Low =1;
//     High =2;
// }

service task{
    rpc CreateTask (createReq) returns (createRes);
    rpc GetAllTask (getAllReq) returns (getAllRes);
    rpc GetOne (getOneReq) returns (getOneRes);
    rpc Update (updateReq) returns (updateRes);
    rpc Remove (removeReq) returns (removeRes);
}

message createReq {
    string title = 1;
    string description = 2;
    string status =3;
    string priority =4;
    string due_date = 5;
    string reminder_at = 6;
    string owner_id = 7; 
}

message createRes{
    string id = 1;
    string owner_id = 2;
    string title = 3;
    string description =4;
    string status = 5;
    string priority =6;
    string due_date =7;
    string reminder_at = 8;
    string reminder_status =9;
    string created_at =10;
    string updated_at = 11;

}

message getAllReq {
    string owner_id = 1;
    string status = 2;     
    string priority = 3; 
    int32 page = 4;
    int32 limit = 5;
    string sort_by = 6;
    string order = 7;
}

message getAllRes{
    int32 count = 1;
    repeated createRes tasks = 2;
}

message getOneReq {
    string id =1;
    string user_id =2;

}

message getOneRes {
    createRes task = 1;
}

message updateReq {
  string id = 1;
  string user_id =2;
  string title = 3;
  string description = 4;
  string status = 5;
  string priority = 6;
  string due_date = 7;
  string reminder_at = 8;
  

}

message updateRes{
    createRes task = 1;
}

message removeReq {
    string id = 1;
    string user_id =2;
}

message removeRes {
string message = 1;
}